/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        outline: "#727785",
        "secondary-fixed": "#e1e0ff",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#c0c1ff",
        "primary-fixed": "#d8e2ff",
        "on-primary-fixed-variant": "#004395",
        "on-secondary": "#ffffff",
        "on-background": "#191c1d",
        "surface-container": "#edeeef",
        primary: "#0058be",
        "surface-container-low": "#f3f4f5",
        "surface-container-highest": "#e1e3e4",
        "primary-fixed-dim": "#adc6ff",
        "on-tertiary-container": "#fffbff",
        "surface-bright": "#f8f9fa",
        secondary: "#4648d4",
        "outline-variant": "#c2c6d6",
        "on-surface-variant": "#424754",
        "on-primary-fixed": "#001a42",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#ffb786",
        tertiary: "#924700",
        "on-tertiary-fixed-variant": "#723600",
        "surface-tint": "#005ac2",
        "on-secondary-fixed-variant": "#2f2ebe",
        error: "#ba1a1a",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "surface-variant": "#e1e3e4",
        "on-primary-container": "#fefcff",
        "on-tertiary-fixed": "#311400",
        background: "#f8f9fa",
        "error-container": "#ffdad6",
        "primary-container": "#2170e4",
        "surface-container-high": "#e7e8e9",
        "inverse-on-surface": "#f0f1f2",
        "tertiary-container": "#b75b00",
        "on-secondary-container": "#fffbff",
        "inverse-primary": "#adc6ff",
        "tertiary-fixed": "#ffdcc6",
        "surface-dim": "#d9dadb",
        "on-surface": "#191c1d",
        "secondary-container": "#6063ee",
        "inverse-surface": "#2e3132",
        "on-secondary-fixed": "#07006c",
        surface: "#f8f9fa",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "h1": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "h2": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "h3": ["20px", { lineHeight: "28px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
